### ISSUE TITLE
Several repos :'(

### ISSUE THREAD

**Issue by Neustradamus** [Fiber-cyber/catalog#49]
@Fiber-cyber: In first, I wish you a Happy New Year!

Happy to see your development!

Hard to see differences with official place.

Maybe good to harmonize?

But there is with a lot of tickets, forks, etc:
- https://github.com/gburton/CE-Phoenix

Official here: https://github.com/CE-PhoenixCart

Other team members:
- https://github.com/heatherbellho
- https://github.com/ecartz

I have done some tickets about this problem...

**Comment by Fiber-cyber** [comment]
Can be confusing, but if you look closely you will see that my version is the Dutch translation :-)
